apiVersion: apps/v1
kind: Deployment
metadata:
  name: animebook-post-deployment
  labels:
    app: animebook-post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: animebook-post
  template:
    metadata:
      labels:
        app: animebook-post
    spec:
      containers:
        - name: animebook-post
          image: agalex/animebook-post:ci
          ports:
            - containerPort: 3000
          command: ["/bin/sh"]
          args: ["-c", "npx sequelize-cli db:migrate && node server.js"]
          readinessProbe:
            httpGet:
              port: 3000
              path: /health-check
            initialDelaySeconds: 1
            periodSeconds: 5
            timeoutSeconds: 4
            successThreshold: 2
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: post-db-secret
                  key: user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: post-db-secret
                  key: password
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: post-db-config
                  key: url
            - name: MESSAGE_BROKER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: connection
---
apiVersion: v1
kind: Service
metadata:
  name: animebook-post-service
spec:
  selector:
    app: animebook-post
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
