# Use postgres/example user/password credentials
version: '3.1'

services:
  post-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: postdb
    ports:
      - "5432:5432"
